version: '3.8'
services:
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/user-service/.env
    restart: always

  wallet-service:
    build: ./services/wallet-service
    ports:
      - "3002:3002"
    env_file:
      - ./services/wallet-service/.env

  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "3004:3004"
    env_file:
      - ./services/notification-service/.env
    restart: always

  dispute-service:
    build:
      context: ./services/dispute-service
    ports:
      - "3005:3005"
    env_file:
      - ./services/dispute-service/.env
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - wallet-service
      - dispute-service
      - notification-service
    env_file:
      - ./api-gateway/.env

volumes:
  mysql_data: