services:
  - type: pserv
    name: fintech-db
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVarGroups: Coinflux-1
    rootDir: services/fintech-db/

  - type: web
    name: user-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVarGroups: Coinflux-1
    rootDir: services/user-service/

  - type: web
    name: wallet-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/wallet-service/
    envVarGroups: Coinflux-1

  - type: web
    name: notification-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/notification-service/
    envVarGroups: Coinflux-1