services:
  - type: pserv
    name: fintech-db
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/fintech-db/
    envVars:
      - fromGroup: Coinflux-1

  - type: web
    name: user-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/user-service/
    envVars:
      - fromGroup: Coinflux-1

  - type: web
    name: wallet-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/wallet-service/
    envVars:
      - fromGroup: Coinflux-1

  - type: web
    name: notification-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/notification-service/
    envVars:
      - fromGroup: Coinflux-1