services:

  - type: web
    name: user-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/user-service/
    envVars:
      - fromGroup: Coinflux-1

  - type: web
    name: wallet-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/wallet-service/
    envVars:
      - fromGroup: Coinflux-1

  - type: web
    name: notification-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/notification-service/
    envVars:
      - fromGroup: Coinflux-1

  - type: web
    name: dispute-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/dispute-service/
    envVars:
      - fromGroup: Coinflux-1

  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: api-gateway/
    envVars:
      - fromGroup: Coinflux-1