services:
  - type: web
    name: user-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/user-service/
    envVars:
      - key: PORT
        value: 3001
      - key: DB_HOST
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: DB_USER
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: DB_PASS
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: DB_NAME
        value: auth_db
      - key: JWT_SECRET
        value: ""   # ⚠️ Set this in Render Dashboard

  - type: web
    name: wallet-service
    env: docker
    dockerfilePath: ./services/wallet-service/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3002
      - key: DB_HOST
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: DB_USER
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: DB_PASS
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: DB_NAME
        value: wallet_db
      - key: JWT_SECRET
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: RABBITMQ_URL
        value: ""   # ⚠️ Set this in Render Dashboard

  - type: web
    name: notification-service
    env: docker
    dockerfilePath: ./services/notification-service/Dockerfile
    plan: free
    envVars:
      - key: MAIL_USER
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: MAIL_PASS
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: RABBITMQ_URL
        value: ""   # ⚠️ Set this in Render Dashboard