databases:
  - name: fintech
    databaseName: fintech
    user: root
    plan: free
    ipAllowList: 0.0.0.0/0
    mysql: true

services:
  - type: web
    name: user-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/user-service/
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: fintech
          property: host
      - key: DB_USER
        fromDatabase:
          name: fintech
          property: root
      - key: DB_PASS
        fromDatabase:
          name: fintech
          property: password
      - key: DB_NAME
        fromDatabase:
          name: fintech
          property: fintech
      - key: JWT_SECRET
        value: ""

  - type: web
    name: wallet-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/wallet-service/
    envVars:
      - key: PORT
        value: 3002
      - key: DB_HOST
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: DB_USER
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: DB_PASS
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: DB_NAME
        value: wallet_db
      - key: JWT_SECRET
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: RABBITMQ_URL
        value: ""   # ⚠️ Set this in Render Dashboard

  - type: web
    name: notification-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/notification-service/
    envVars:
      - key: MAIL_USER
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: MAIL_PASS
        value: ""   # ⚠️ Set this in Render Dashboard
      - key: RABBITMQ_URL
        value: ""   # ⚠️ Set this in Render Dashboard