services:
  - type: background
    name: mysql-db
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVarsGroup: Coinflux-1
    rootDir: services/fintech-db/

  - type: web
    name: user-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVarsGroup: Coinflux-1
    rootDir: services/user-service/

  - type: web
    name: wallet-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/wallet-service/
    envVarsGroup: Coinflux-1

  - type: web
    name: notification-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: services/notification-service/
    envVarsGroup: Coinflux-1